import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const handleButtonClick = async () => {
    const { title } = await fetch(
      "https://jsonplaceholder.typicode.com/todos/1"
    ).then((it) => it.json());

    window.navigator.clipboard
      .writeText(title)
      .then((_) => alert("copiado com sucesso"))
      .catch((_) => alert("erro ao copiar"));
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={handleButtonClick}>botao</button>
      </main>
    </div>
  );
};

export default Home;
